### PR TITLE
 Add welcome YouTube videos

### PR DESCRIPTION
**Pull request by typokign**
### Administrative Info
Monday Board ID: 853642866

### Changes
What changes did you make?
- Added welcome YouTube videos to the top of the home screen

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

image

### CODE REVIEW

**Review by aksharans — DISMISSED** [review]
LGTM (on ios)

**Review by aksharans — DISMISSED** [review]
LGTM, only thing is I'm not sure if you wanted to add a textAlign:center/paddingHorizontal to the videoTitle style to center the titles (the 2nd line of the 2nd title was aligned to the left).

**Review by aksharans — APPROVED** [review]
LGTM

**Review by Anshul-Birla — APPROVED** [review]
Everything looks good and the videos play and work well. Looks accurate for the style guide, but maybe in the future, do we want to have like a shadow on the videos or something? They look kinda flat. Maybe even make them slightly bigger.

**Comment by dacruz21** [comment]
Good idea, I'm gonna merge this mainly for the font fixes but I'll come back to the shadows for sure

**Pull request merged**
