### PR TITLE
Move home screen page numbers outside ScrollView

### PR DESCRIPTION
**Pull request by typokign**
### Administrative Info
Monday Board ID: 853642866

### Changes
At design team's request, move the page numbers outside of the
ScrollView, and replace the arrows with "Page M of N"

### Confirmation of Change 
Screenshot_20210503-190550

### CODE REVIEW

**Review by aksharans — CHANGES_REQUESTED** [review]
Looks good, but the only thing is that when there are no results, the page numbers jump to the top and shows page 1 of 0:
   
image


I think this is because the no results screen is in the home page, so when there are no books, the paginated booklist scrollview becomes a null component, and the page number view renders then the no results renders.  

Could a fix be bookPages.length !== 0 && {View for pagesMofN} ?

**Comment by dacruz21** [comment]
Good catch, that's exactly what I'll do :)

**Review by aksharans — APPROVED** [review]
LGTM

**Review by allisonbhavsar — APPROVED** [review]
Looks great!

**Pull request merged**
