### PR TITLE
App login/signup screens with Firebase Auth

### PR DESCRIPTION
**Pull request by typokign**
### Administrative Info
Monday Board ID: 853642866

### Changes
What changes did you make?

- Set up the global AuthContext and routing for authentication
- Create the Welcome, Login, and Signup screens
- Show email, logout, and toggle in San Diego buttons in profile settings

### Testing
How did you confirm your changes worked? 
- Needs to be run against a local backend for CORS to work sadly

### CODE REVIEW

**Review by aksharans — APPROVED** [review]
LGTM

**Review by dhrvsood — APPROVED** [review]
lgtm

**Review by Anshul-Birla — COMMENTED** [review]
lgtm lets get this bread

**Review by Anshul-Birla — APPROVED** [review]
lgtm

**Pull request merged**
